apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: kube-dlvv
data:
  index.html: |
    <html>
      <head>
        <title>Kube dans la vrai vie</title> 
      </head>
      <body style="background-color: lightblue;">
        <marquee behavior="alternate" scrolldelay="30" truespeed>
          <span style="color: red; font-size: xxx-large;">
            KUBE DANS LA VRAIE VIE
          </span>
        </marquee>
      </body>
    </html> 
  page2.html: uegfzuefze